// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProjectImage(arg1) {
  return window['go']['main']['App']['AddProjectImage'](arg1);
}

export function AddProjectImages(arg1) {
  return window['go']['main']['App']['AddProjectImages'](arg1);
}

export function DeleteProjectImage(arg1) {
  return window['go']['main']['App']['DeleteProjectImage'](arg1);
}

export function ExportGameXLSX(arg1) {
  return window['go']['main']['App']['ExportGameXLSX'](arg1);
}

export function ExportXLSX(arg1, arg2) {
  return window['go']['main']['App']['ExportXLSX'](arg1, arg2);
}

export function GeneratePDF(arg1) {
  return window['go']['main']['App']['GeneratePDF'](arg1);
}

export function GetExcelHeaders(arg1, arg2) {
  return window['go']['main']['App']['GetExcelHeaders'](arg1, arg2);
}

export function GetPDFLayout(arg1) {
  return window['go']['main']['App']['GetPDFLayout'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportCardsWithMapping(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportCardsWithMapping'](arg1, arg2, arg3);
}

export function ListProjectImages() {
  return window['go']['main']['App']['ListProjectImages']();
}

export function LoadGame() {
  return window['go']['main']['App']['LoadGame']();
}

export function LoadImageAsDataURL(arg1) {
  return window['go']['main']['App']['LoadImageAsDataURL'](arg1);
}

export function NewGame() {
  return window['go']['main']['App']['NewGame']();
}

export function ReplaceProjectImage(arg1, arg2) {
  return window['go']['main']['App']['ReplaceProjectImage'](arg1, arg2);
}

export function ResolveImagePath(arg1) {
  return window['go']['main']['App']['ResolveImagePath'](arg1);
}

export function SampleDeck() {
  return window['go']['main']['App']['SampleDeck']();
}

export function SaveGame(arg1) {
  return window['go']['main']['App']['SaveGame'](arg1);
}

export function SaveImages(arg1) {
  return window['go']['main']['App']['SaveImages'](arg1);
}

export function SelectExcelFile() {
  return window['go']['main']['App']['SelectExcelFile']();
}

export function SelectFontFile() {
  return window['go']['main']['App']['SelectFontFile']();
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}

export function SelectImageFiles() {
  return window['go']['main']['App']['SelectImageFiles']();
}
