// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportXLSX(arg1, arg2) {
  return window['go']['main']['App']['ExportXLSX'](arg1, arg2);
}

export function GeneratePDF(arg1) {
  return window['go']['main']['App']['GeneratePDF'](arg1);
}

export function GetPDFLayout(arg1) {
  return window['go']['main']['App']['GetPDFLayout'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportXLSX() {
  return window['go']['main']['App']['ImportXLSX']();
}

export function LoadGame() {
  return window['go']['main']['App']['LoadGame']();
}

export function LoadImageAsDataURL(arg1) {
  return window['go']['main']['App']['LoadImageAsDataURL'](arg1);
}

export function SampleDeck() {
  return window['go']['main']['App']['SampleDeck']();
}

export function SaveGame(arg1) {
  return window['go']['main']['App']['SaveGame'](arg1);
}

export function SelectFontFile() {
  return window['go']['main']['App']['SelectFontFile']();
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}
