// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {deck} from '../models';
import {cards} from '../models';

export function ExportXLSX(arg1:Array<deck.Card>,arg2:Array<deck.FieldDefinition>):Promise<void>;

export function GeneratePDF(arg1:deck.Deck):Promise<void>;

export function GetPDFLayout(arg1:deck.Deck):Promise<deck.PDFLayout>;

export function Greet(arg1:string):Promise<string>;

export function ImportXLSX():Promise<Array<deck.Card>>;

export function LoadDeck():Promise<deck.Deck>;

export function LoadImageAsDataURL(arg1:string):Promise<string>;

export function SampleDeck():Promise<Array<cards.Card>>;

export function SaveDeck(arg1:deck.Deck):Promise<void>;

export function SelectFontFile():Promise<string>;

export function SelectImageFile():Promise<string>;
