// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {game} from '../models';
import {deck} from '../models';
import {cards} from '../models';
import {main} from '../models';

export function AddProjectImage(arg1:string):Promise<string>;

export function AddProjectImages(arg1:Array<string>):Promise<Array<string>>;

export function DeleteProjectImage(arg1:string):Promise<void>;

export function ExportGameXLSX(arg1:game.Game):Promise<void>;

export function ExportXLSX(arg1:Array<deck.Card>,arg2:Array<deck.FieldDefinition>):Promise<void>;

export function GeneratePDF(arg1:deck.Deck):Promise<void>;

export function GetExcelHeaders(arg1:string,arg2:string):Promise<Array<string>>;

export function GetPDFLayout(arg1:deck.Deck):Promise<deck.PDFLayout>;

export function Greet(arg1:string):Promise<string>;

export function ImportCardsWithMapping(arg1:string,arg2:string,arg3:Record<string, string>):Promise<Array<deck.Card>>;

export function ListProjectImages():Promise<Array<string>>;

export function LoadGame():Promise<game.Game>;

export function LoadImageAsDataURL(arg1:string):Promise<string>;

export function NewGame():Promise<void>;

export function ReplaceProjectImage(arg1:string,arg2:string):Promise<void>;

export function ResolveImagePath(arg1:string):Promise<string>;

export function SampleDeck():Promise<Array<cards.Card>>;

export function SaveGame(arg1:game.Game):Promise<void>;

export function SaveImages(arg1:Record<string, string>):Promise<void>;

export function SelectExcelFile():Promise<main.ExcelSelection>;

export function SelectFontFile():Promise<string>;

export function SelectImageFile():Promise<string>;

export function SelectImageFiles():Promise<Array<string>>;
